### ISSUE TITLE
[Enhancement] Update W4 form for 2021

### ISSUE THREAD

**Issue by James1x0** [associatedemployers/igneous#377]

**Comment by JavaLavaMT** [comment]
Error when saving '500 server error'
gets to https://github.com/associatedemployers/igneous/blob/398939e022525693a193a070fb2c5dea0b9b2527/lib/models/file-assignment/middleware/effects/fill-file.js#L59

then 

https://app.logdna.com/e54eec9571/logs/view?t=timestamp%3A1606761218389&a=1606761218389.1286649805516632068&apps=igneous&levels=debug

Error: ENOENT: no such file or directory, open '/api/tmp/b55294c0bf8cf99eb6f1bf0f8fd74b29.pdf'
    at Object.openSync (fs.js:443:3)
    at Object.writeFileSync (fs.js:1194:35)
    at writeTempFile (/api/node_modules/node-pdftk/index.js:72:20)
    at new PdfTk (/api/node_modules/node-pdftk/index.js:89:32)
    at Object.input (/api/node_modules/node-pdftk/index.js:1075:20)
    at model.middleware (/api/lib/models/file-assignment/middleware/effects/fill-file.js:69:6)
    at process._tickCallback (internal/process/next_tick.js:68:7)
  xxx PUT /api/v1/file-assignments/5fbd7c49a619deb08761de40 500 211ms -
